# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lab4wheeleyinstance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lab4wheeleyregname.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c169f1722e194486bba7091f9a6260c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a1b58cf449e14fb9872e3bbff2b74893 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lab4wheeleyregname.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c169f1722e194486bba7091f9a6260c8 }}/lab4wheeley:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lab4wheeleyinstance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8fb74fe253c34184843c5f3ec42bc442 }}
        images: 'lab4wheeleyregname.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c169f1722e194486bba7091f9a6260c8 }}/lab4wheeley:${{ github.sha }}'